apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: game-2048-app     
  namespace: game-2048-ns
spec:
  selector:
    matchExpressions:
      - key: app  
        operator: In
        values:
        - game-2048
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
