apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: game-2048-sub                           
  namespace: game-2048-ns
  labels:
    app: game-2048
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: lab-4-eks-assets
spec:
  channel:  game-2048-ns/game-2048-cha
  placement: 
    placementRef: 
      kind: PlacementRule
      name: env-devonly     
